server:
  port: 9092
camel:
  springboot:
    name: ServicesRest
management:
  port: 8082
endpoints:
  enabled: false
  health:
    enabled: true
quickstart:
  generateOrderPeriod: 10s
  processOrderPeriod: 30s